### ISSUE TITLE
Swap sounds for specific weapons

### ISSUE THREAD

**Issue by AverageToaster** [DominickCobb-rs/Attack-Sound-Notifications#3]
Hey, apologies if this is already handled, but is there any way to configure specific sounds for specific weapons? I can see there's handling for hit, miss, and max for specs, but from what I can tell it there's not specific weapon handling. Like, if I wanted a sound just for DWH, it would affect all spec misses?

**Comment by DominickCobb-rs** [comment]
You should be able to click the grey box on the left side to choose a weapon from the chatbox when logged into the game. Also, apologies if things don't function well, this is my first plugin and I haven't worked on it in a year now.

**Comment by AverageToaster** [comment]
Oh, my bad, I didn't even notice that control. Thanks, apologies for taking up your time from my lack of reading.
